import org.gradle.plugins.ide.idea.model.IdeaLanguageLevel
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
import kotlin.contracts.contract

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
	application
	idea

	kotlin("jvm").version("1.3.21")

	id("org.springframework.boot") version "2.1.2.RELEASE"
	id("io.spring.dependency-management") version "1.0.6.RELEASE"
	id("org.jetbrains.kotlin.plugin.spring") version "1.3.21"

}

repositories {
	// Use jcenter for resolving your dependencies.
	// You can declare any Maven/Ivy/file repository here.
	jcenter()
	mavenCentral()
	maven { url= uri("https://repo.spring.io/snapshot") }
	maven { url= uri("https://repo.spring.io/milestone") }
	maven { url= uri("http://repo.spring.io/release") }

}

val kotlinLoggingVer = "1.6.22"

val javaxAnnotationApiVer = "1.3.2"
val javaxTransactionApiVer = "1.3"

val testContainersVer = "1.10.3"
val jfairyVer = "0.5.9"
val springCloudVersion ="Greenwich.BUILD-SNAPSHOT"


dependencies {
	// Use the Kotlin JDK 8 standard library.
	implementation(kotlin("stdlib-jdk8"))
	implementation(kotlin("reflect"))


	implementation("io.github.microutils:kotlin-logging:$kotlinLoggingVer")

	// Use the Kotlin JUnit integration.
	implementation("com.fasterxml.jackson.module:jackson-module-kotlin")

	implementation("org.springframework.boot:spring-boot-starter-webflux")
	implementation("org.springframework.boot:spring-boot-starter-data-mongodb-reactive")

	testImplementation("org.springframework.boot:spring-boot-starter-test") {
		exclude(group = "junit", module = "junit")
	}
	testImplementation("io.projectreactor:reactor-test")
	testImplementation("org.junit.jupiter:junit-jupiter:5.4.0")
	testImplementation("org.testcontainers:testcontainers:$testContainersVer")
	testImplementation("io.codearte.jfairy:jfairy:$jfairyVer")

	testImplementation("org.springframework.cloud:spring-cloud-starter-contract-stub-runner")
	testImplementation("org.springframework.cloud:spring-cloud-starter-contract-verifier")
	testImplementation("org.springframework.cloud:spring-cloud-contract-gradle-plugin")
}
dependencyManagement {
	val springCloudVersion = "Greenwich.BUILD-SNAPSHOT"
	imports {
		mavenBom("org.springframework.cloud:spring-cloud-dependencies:$springCloudVersion")
	}
}

application {
	mainClassName = "com.example.producer.AppKt"
	applicationName = "app"
	version = "0.1-SNAPSHOT"
	group = "com.example.producer"
}

java {
	sourceCompatibility = JavaVersion.VERSION_11
	targetCompatibility = JavaVersion.VERSION_11
}

idea {
	project {
		languageLevel = IdeaLanguageLevel(JavaVersion.VERSION_11)
	}
	module {
		isDownloadJavadoc = true
		isDownloadSources = true
	}
}

springBoot {
	buildInfo()
}
tasks.withType<Test> {
	useJUnitPlatform()
	testLogging {
		events("passed", "skipped", "failed")
	}
}

tasks.withType<Wrapper> {
	gradleVersion = "5.2.1"
}

// config JVM target to 1.8 for kotlin compilation tasks
tasks.withType(KotlinCompile::class).all {
	kotlinOptions {
		jvmTarget = "1.8"
	}
}
//contract {
//
//}

