/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.example.producer

import org.springframework.boot.SpringApplication
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration
import org.springframework.http.MediaType
import org.springframework.web.reactive.function.server.RouterFunction
import org.springframework.web.reactive.function.server.ServerResponse
import org.springframework.web.reactive.function.server.router

@SpringBootApplication
class App


fun main(args: Array<String>) {
	runApplication<App>(*args)
}


@Configuration
class ReservationRestConfiguration {

	@Bean
	fun route(repository: ReservationRepository) = router {
		    accept(MediaType.APPLICATION_JSON_UTF8).nest {
			    GET("/reservations") { _ -> ServerResponse.ok().body(repository.findAll(), Reservation::class.java) }
		    }
		}

}

